const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/**',route=>route.request().method()==='GET'?route.continue():route.abort());
 await page.goto('http://127.0.0.1:8765/#data');
 await page.locator('#scope-select').selectOption('EQUITY/GLB/1/MINVOL10M');
 await page.locator('#catalog-category').selectOption('fundamental');
 await page.locator('tr').filter({hasText:'Global Fundamental Data'}).getByRole('button',{name:'Open fields',exact:true}).click();
 await page.getByRole('button',{name:'Export dataset as JSON',exact:true}).waitFor();
 assert.equal(await page.locator('#catalog-alpha-above').inputValue(),'5');
 assert.equal(await page.locator('#catalog-alpha-below').inputValue(),'500');
 const data=await (await page.request.get('http://127.0.0.1:8765/api/catalog/browse?scope_id=EQUITY/GLB/1/MINVOL10M&kind=fields&dataset_id=fundamental28&alpha_count_above=5&alpha_count_below=500')).json();
 assert.ok(data.results.every(f=>f.alphaCount>5&&f.alphaCount<500));
 const downloadPromise=page.waitForEvent('download');
 await page.getByRole('button',{name:'Export dataset as JSON',exact:true}).click();
 const download=await downloadPromise;
 const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
 assert.equal(exported.field_count,data.count);
 assert.equal(exported.fields.length,data.count);
 assert.equal(exported.dataset.id,'fundamental28');
 assert.ok(exported.fields.every(f=>f.alphaCount>5&&f.alphaCount<500));
 const lowerCleared=page.waitForResponse(r=>r.url().includes('/api/catalog/browse')&&!r.url().includes('alpha_count_above')&&r.url().includes('alpha_count_below'));
 const unboundedResponse=page.waitForResponse(r=>r.url().includes('/api/catalog/browse')&&!r.url().includes('alpha_count_below')&&!r.url().includes('alpha_count_above'));
 await page.locator('#catalog-alpha-above').fill('');await page.locator('#catalog-alpha-above').press('Tab');
 await lowerCleared;
 await page.waitForFunction(()=>document.querySelector('#catalog-alpha-above')?.value==='');
 await page.waitForTimeout(100);
 await page.locator('#catalog-alpha-below').fill('');await page.locator('#catalog-alpha-below').press('Tab');
 await unboundedResponse;
 await page.getByRole('columnheader',{name:'Alphas',exact:true}).waitFor();
 await page.screenshot({path:'data/previews/catalog-alpha-count.png',fullPage:true});
 assert.deepEqual(errors,[]);
 await browser.close();console.log('Passed: alpha-count defaults, strict filtering, full JSON download and clearing bounds.');
})().catch(e=>{console.error(e);process.exit(1)});
